// <auto-generated />
using System;
using ERecruitment.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERecruitment.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102190844_AddUniqueConstraintJobApplications")]
    partial class AddUniqueConstraintJobApplications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERecruitment.Web.Models.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.AuditEntry", b =>
                {
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Actor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TimestampUtc", "Actor", "Action");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.EmailDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyPreview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailDeliveries");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId", "JobPostingId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobApplications_ApplicantId_JobPostingId_Unique")
                        .HasFilter("[Status] != 5");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApplicationEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Centre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DutiesDescription")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnquiriesContactPerson")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EnquiriesPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KillerQuestions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryRange")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.PasswordReset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.Applicant", b =>
                {
                    b.OwnsOne("ERecruitment.Web.Models.ApplicantProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("AvailabilityDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("AvailabilityNotice")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BusinessDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("BusinessWithState")
                                .HasColumnType("bit");

                            b1.Property<string>("ContactEmail")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CriminalRecordDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DateOfBirth")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("DeclarationAccepted")
                                .HasColumnType("bit");

                            b1.Property<DateTime?>("DeclarationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DepartmentName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DisabilityDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DischargedDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("DischargedForIllHealth")
                                .HasColumnType("bit");

                            b1.Property<string>("DismissedDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("DismissedForMisconduct")
                                .HasColumnType("bit");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("HasCriminalRecord")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasDisability")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasPendingCase")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasWorkPermit")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsSouthAfrican")
                                .HasColumnType("bit");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Location")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nationality")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PassportNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PendingCaseDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PendingDisciplinaryCase")
                                .HasColumnType("bit");

                            b1.Property<string>("PendingDisciplinaryDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PositionName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PreferredLanguage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("PrivateSectorYears")
                                .HasColumnType("int");

                            b1.Property<string>("ProfessionalInstitution")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("ProfessionalRegistrationDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ProfessionalRegistrationNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("PublicSectorYears")
                                .HasColumnType("int");

                            b1.Property<bool>("ReappointmentCondition")
                                .HasColumnType("bit");

                            b1.Property<string>("ReappointmentConditionDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReappointmentDepartment")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReferenceNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("ResignedPendingDisciplinary")
                                .HasColumnType("bit");

                            b1.Property<string>("ResignedPendingDisciplinaryDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SaIdNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SignatureData")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("WillRelinquishBusiness")
                                .HasColumnType("bit");

                            b1.Property<string>("WorkPermitDetails")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsOne("ERecruitment.Web.Models.StoredDocument", "AdditionalDocument", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileApplicantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("DocumentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StorageToken")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("UploadedAtUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ApplicantProfileApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileApplicantId");
                                });

                            b1.OwnsOne("ERecruitment.Web.Models.StoredDocument", "DriversLicenseDocument", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileApplicantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("DocumentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StorageToken")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("UploadedAtUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ApplicantProfileApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileApplicantId");
                                });

                            b1.OwnsOne("ERecruitment.Web.Models.StoredDocument", "IdDocument", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileApplicantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("DocumentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StorageToken")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("UploadedAtUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ApplicantProfileApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileApplicantId");
                                });

                            b1.OwnsOne("ERecruitment.Web.Models.StoredDocument", "QualificationDocument", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileApplicantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("DocumentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StorageToken")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime>("UploadedAtUtc")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ApplicantProfileApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileApplicantId");
                                });

                            b1.OwnsOne("ERecruitment.Web.Models.CvDocument", "Cv", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileApplicantId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContentType")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FileName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ParsedSummary")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StorageToken")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ApplicantProfileApplicantId");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileApplicantId");
                                });

                            b1.OwnsMany("ERecruitment.Web.Models.LanguageProficiency", "Languages", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("LanguageName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ReadWriteProficiency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("SpeakProficiency")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ApplicantProfileId", "Id");

                                    b2.ToTable("LanguageProficiency");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileId");
                                });

                            b1.OwnsMany("ERecruitment.Web.Models.QualificationRecord", "Qualifications", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("InstitutionName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("QualificationName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("StudentNumber")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("YearObtained")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ApplicantProfileId", "Id");

                                    b2.ToTable("QualificationRecord");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileId");
                                });

                            b1.OwnsMany("ERecruitment.Web.Models.ReferenceContact", "References", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("ContactNumber")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Relationship")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ApplicantProfileId", "Id");

                                    b2.ToTable("ReferenceContact");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileId");
                                });

                            b1.OwnsMany("ERecruitment.Web.Models.WorkExperienceRecord", "WorkExperience", b2 =>
                                {
                                    b2.Property<Guid>("ApplicantProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("EmployerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime?>("FromDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("PositionHeld")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ReasonForLeaving")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<DateTime?>("ToDate")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("ApplicantProfileId", "Id");

                                    b2.ToTable("WorkExperienceRecord");

                                    b2.WithOwner()
                                        .HasForeignKey("ApplicantProfileId");
                                });

                            b1.Navigation("AdditionalDocument");

                            b1.Navigation("Cv");

                            b1.Navigation("DriversLicenseDocument");

                            b1.Navigation("IdDocument");

                            b1.Navigation("Languages");

                            b1.Navigation("QualificationDocument");

                            b1.Navigation("Qualifications");

                            b1.Navigation("References");

                            b1.Navigation("WorkExperience");
                        });

                    b.OwnsOne("ERecruitment.Web.Models.EquityDeclaration", "EquityDeclaration", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ConsentGiven")
                                .HasColumnType("bit");

                            b1.Property<string>("DisabilityStatus")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ethnicity")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Gender")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.Navigation("EquityDeclaration");

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("ERecruitment.Web.Models.AuditEntry", b =>
                {
                    b.HasOne("ERecruitment.Web.Models.JobApplication", null)
                        .WithMany("AuditTrail")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ERecruitment.Web.Models.JobApplication", b =>
                {
                    b.HasOne("ERecruitment.Web.Models.Applicant", null)
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsMany("ERecruitment.Web.Models.ScreeningAnswer", "ScreeningAnswers", b1 =>
                        {
                            b1.Property<Guid>("JobApplicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Answer")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool?>("MeetsRequirement")
                                .HasColumnType("bit");

                            b1.Property<int>("Order")
                                .HasColumnType("int");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("JobApplicationId", "Id");

                            b1.ToTable("ScreeningAnswer");

                            b1.WithOwner()
                                .HasForeignKey("JobApplicationId");
                        });

                    b.Navigation("ScreeningAnswers");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("ERecruitment.Web.Models.JobApplication", b =>
                {
                    b.Navigation("AuditTrail");
                });
#pragma warning restore 612, 618
        }
    }
}
